### ISSUE TITLE
ffmpeg error, won't combine parts

### ISSUE THREAD

**Issue by Minkafighter** [ArneVogel/concat#12]
trying to download a vod, when finished downloading it tries to combine the parts but it throws an ffmpeg error as shown below.
`./concat_ubuntu -vod=111836368 -start="0 0 0"`

> ......................................................
>Combining parts
>
>ffmpeg error
>Deleting chunks
>Deleting temp dir
>All done!
>root@vps:~/twitch#

This only happens on "long" vods. It doesnt happen on https://www.twitch.tv/videos/112067373 .

**Comment by ArneVogel** [comment]
This might be caused by ubuntus limit on open files. Long vods can have over 4096 chunks that have to be combined by ffmpeg. My guess is that ffmpeg opens all the chunks during the combining process and this caused an error from ubuntu. I had similar problems with the file limit on ubuntu before.

Can you increase the open file limit and try again?

**Comment by Minkafighter** [comment]
This sadly didnt work:

> ........................
>Combining parts
>
>ffmpeg error
>Deleting chunks
>Deleting temp dir
>All done!
>minka@vps:~$ ulimit -n
>512000
>minka@vps:~$

Is there a way to tell the program to download bigger chunks? Or tell ffmpeg to only combine 2000 or 4000 chunks at once?

**Comment by Minkafighter** [comment]
I found something... on openVZ i guess you cant change the open file limit, as you dont have access to enter this command:

root@vps:~# sudo sysctl -w fs.file-max=1024
sysctl: permission denied on key 'fs.file-max'

Entering this command in a KVM server, will result in no "permission denied" and i can combine all parts! Yay, i guess! :D
